### ISSUE TITLE
Can you please share some examples to use this with java

### ISSUE THREAD

**Issue by parth2545** [tyczj/Tweedle#2]
I am trying to use this amazing library but I am not able to.There are various problems appearing.I am not that good at kotlin so can you help me out with how we can use this library with java android applications.

**Comment by tyczj** [comment]
This is a kotlin library and wont work with Java because it uses Kotlin Coroutines among other kotlin only features

**Comment by parth2545** [comment]
Hi,

Sorry to bother you, but I am new to android development. Your library is
perfect for the app i am trying to develop. But my app is in java and i
read everywhere that i can combine kotlin classes in java. So if i create a
kotlin class and called it in maniactivity..it won't work???

I am sorry again but little bit guidance will help me lot.


Thank you and have a nice day.

**Comment by tyczj** [comment]
Yes you can use kotlin classes in Java but there are certain things in kotlin you cannot use in Java that this library uses

**Comment by parth2545** [comment]
Ohh, Ohkay..
Thank you so much..i was trying from last two days to work with it.
Thanks a lot.

**Comment by parth2545** [comment]
Hi, Sorry to bother you again. I used your library in the Kotlin project
now. It is working excellent. But I was trying to find if there is a way to
just remove tweet from multitweetpayload.  I used ( It.data.data.text) but
for some reason it is not working.

Do let me know. Thank you.

Also, With some changes , we can use this library for twitter API 1.1 all
end points. I tried that and it worked.

**Comment by tyczj** [comment]
Not sure I understand what you are trying to do. Can you give an example

**Comment by parth2545** [comment]
When I am using ( Response.success -> it.data ) I get this result
![image](https://user-images.githubusercontent.com/73188554/97086611-422be380-161c-11eb-9836-4841b6251a80.png)


But I want to extract just tweet text from it . Therefore I am trying to
use ( Response.Success -> it.data.data.text ) from your examples. But it is
not working
![image](https://user-images.githubusercontent.com/73188554/97086595-1c064380-161c-11eb-885e-87ac7445101c.png)

So I am asking if there is a inbuilt  way to extract tweet text from
MultiTweetPayload or do I have to build another method to parse that json
output.

**Comment by tyczj** [comment]
I cannot see your images you are trying to post.

A MultiTweetPayload can have one or many results you will have to loop through the list to get all the tweets or a specific one

**Comment by parth2545** [comment]
I have updated the last one.

Okay so for looping Multitweetpayload , I have to write different coroutine code ,right?

Sorry again to make it so confusing.

**Comment by tyczj** [comment]
all you have to do is 

```
it.data.data.forEach{tweetData ->

    tweetData.text //your tweet text

}
```

Nothing to do with coroutines its basic looping

**Comment by parth2545** [comment]
How can I use the function in kotlin in background?? 
For example : 
`fun Tweeter() {
        val token ="
        val query = "\"Now that Tesla FSD beta\"from:elonmusk"
        
        var mainActivityViewModel = ViewModelProvider(this).get(MainViewModel::class.java)

        val map = HashMap<String, String>()

        val dal = mainActivityViewModel.getRecentTweets(token, query, map).observe(this, Observer {
            when (it) {
                is Response.Error -> {
                    it.exception
                }
                is Response.Success -> it.data.data.forEach { tweetdata -> tweetdata.text }
            }
        })
    }`

I should be able to call this function in background even without oncreat? Is that possible?

**Comment by tyczj** [comment]
it is already executing in the background. if you mean looping through the data you get back from the api then look up how to use kotlin coroutines or other threading methods

**Comment by parth2545** [comment]
I meant , how can I use this function without app instance. Like without having app layout on UI?? 

 For ex. My app takes photo , and  find out twitter handle in and find if that twitter handle is verified? but once I take photo my app get closed . No app Interface is shown after that and then notification pops up once it checks if it is verified or not. So I want these functions to run in background but it opens the UI everytime or needs me to write oncreate method..

**Comment by tyczj** [comment]
You will need to use a service or something, these questions are all questions more suited for stackoverflow as they dont really have anything to do with the library
